### ISSUE TITLE
Unable to set up a sync

### ISSUE THREAD

**Issue by bnjbvr** [cozy-labs/cozy-fuse#14]
When doing: 
`cozy-fuse configure https://cozy.example.com mac-linux /home/me/cozy-sync`

I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/cozy-fuse", line 9, in <module>
    load_entry_point('cozy-fuse==0.1.2', 'console_scripts', 'cozy-fuse')()
  File "/usr/local/lib/python2.7/dist-packages/cozyfuse/__main__.py", line 174, in main
    args.func(**args_dict)
  File "/usr/local/lib/python2.7/dist-packages/cozyfuse/actions.py", line 230, in configure_new_device
    local_config.add_config(name, url, path, db_login, db_password)
NameError: global name 'name' is not defined
```

In .cozyfuse/cozyfuse.log, I have:

```
2014-07-21 22:55:28,443 INFO [DB] Database mac-linux created
2014-07-21 22:55:28,486 INFO [DB] Folder design document created
2014-07-21 22:55:28,526 INFO [DB] File design document created
2014-07-21 22:55:28,566 INFO [DB] Device design document created
2014-07-21 22:55:28,606 INFO [DB] Binary design document created
2014-07-21 22:55:29,166 INFO [DB] Db user created
2014-07-21 22:55:29,166 INFO [DB] Local database mac-linux initialized
```

Any idea of what's going on?

**Comment by frankrousseau** [comment]
Thank you @bnjbvr for the report. I think I fix it with my latest commit ( Could you try again with the repository version (03c7e5f79f02a23e019cfd95847e6b1b29b7319d)?

**Comment by bnjbvr** [comment]
Thanks, it works!
