### ISSUE TITLE
Random errors 500 in proxy when using cozy-fuse

### ISSUE THREAD

**Issue by bnjbvr** [cozy-labs/cozy-fuse#15]
When setting up cozy-fuse and a sync and mounting a device, I've hit a lot of errors 500 in the cozy-proxy app and had to restart it a few times. Sorry I don't have a lot to give you for this report, as the production.log got clobbered on every restart and I didn't save it beforehand.

**Comment by Kloadut** [comment]
More precisely, it gives you something like this: 

```
# cozy-fuse configure http://localhost:9104 local /mnt/local
Welcome to Cozy Fuse!

Let's go configuring your new Cozy connection...
Step 1 succeeded: Local configuration created
Type your Cozy password to register your device remotely:

Step 2 succeeded: Device registered remotely.

Now running the first time replication (it could be very long)...
Replication from remote to local...
Traceback (most recent call last):
  File "/usr/local/bin/cozy-fuse", line 9, in <module>
    load_entry_point('cozy-fuse==0.1.2', 'console_scripts', 'cozy-fuse')()
  File "/usr/local/lib/python2.7/dist-packages/cozyfuse/__main__.py", line 174, in main
    args.func(**args_dict)
  File "/usr/local/lib/python2.7/dist-packages/cozyfuse/actions.py", line 283, in configure_new_device
    init_replication(device)
  File "/usr/local/lib/python2.7/dist-packages/cozyfuse/actions.py", line 88, in init_replication
    to_local=True, continuous=False, deleted=False)
  File "/usr/local/lib/python2.7/dist-packages/cozyfuse/replication.py", line 61, in replicate
    filter=filter_name)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/client.py", line 226, in replicate
    status, headers, data = self.resource.post_json('_replicate', data)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 559, in post_json
    **params)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 578, in _request_json
    headers=headers, **params)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 574, in _request
    credentials=self.credentials)
  File "/usr/local/lib/python2.7/dist-packages/couchdb/http.py", line 430, in request
    raise ServerError((status, error))
couchdb.http.ServerError: (500, (u'error', u'Could not open source database `https://localll:*****@localhost:9104/cozy/`: {\'EXIT\',{http_request_failed,"HEAD",\n                             "https://local:*****@localhost:9104/cozy/",\n                             {error,{error,{conn_failed,{error,closed}}}}}}'))
```

Logs of the Data-System (nothing abnormal):

```
[2014-08-01 11:50:08:110] info - helper/db_feed | Publishing usage.application 0.orrin5yxqkvdvx6r
POST /request/user/all/ 200 5.925 ms - 429
[2014-08-01 11:50:08:207] info - helper/db_feed | Publishing usage.application proxy
[2014-08-01 11:50:08:229] info - helper/db_feed | Publishing device.create c581491e42ef76c713b8ab2bf1066fe0
POST /device/ 200 27.383 ms - 170
[2014-08-01 11:50:08:243] info - helper/db_feed | Publishing usage.application 0.orrin5yxqkvdvx6r
POST /request/device/all/ 200 14.757 ms - 787
```

Logs of server's CouchDB:

```
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.9925.0>] 127.0.0.1 - - GET /cozy/_design/user/_view/all 200
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.9931.0>] 127.0.0.1 - - GET /cozy/_design/device/_view/byLogin?key=%22local%22 200
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.13550.0>] 127.0.0.1 - - POST /cozy// 201
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.9927.0>] 127.0.0.1 - - GET /cozy/_design/c581491e42ef76c713b8ab2bf1066fe0 404
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.9929.0>] 127.0.0.1 - - GET /cozy/c581491e42ef76c713b8ab2bf1066fe0 200
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.10727.0>] 127.0.0.1 - - PUT /cozy/_design/c581491e42ef76c713b8ab2bf1066fe0 201
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.9862.0>] 127.0.0.1 - - GET /cozy/_design/c581491e42ef76c713b8ab2bf1066fe0 200
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.9924.0>] 127.0.0.1 - - GET /cozy/_design/device/_view/all 200
```

Log of client's CouchDB:

```
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2782.0>] 127.0.0.1 - - PUT /local 201
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2782.0>] 127.0.0.1 - - HEAD /local 200
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2783.0>] 127.0.0.1 - - HEAD /local 200
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2783.0>] 127.0.0.1 - - PUT /local/_design/folder 201
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2783.0>] 127.0.0.1 - - PUT /local/_design/file 201
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2783.0>] 127.0.0.1 - - PUT /local/_design/device 201
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2783.0>] 127.0.0.1 - - PUT /local/_design/binary 201
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2319.0>] 127.0.0.1 - - POST /_users 201
[Fri, 01 Aug 2014 11:50:06 GMT] [info] [<0.2823.0>] 127.0.0.1 - - PUT /local/_security 200
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 0.25 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:50:08 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 0.5 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:50:09 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 1.0 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:50:10 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 2.0 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:50:12 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 4.0 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:50:16 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 8.0 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:50:24 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 16.0 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:50:40 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 32.0 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:51:12 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 64.0 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:52:16 GMT] [info] [<0.2821.0>] Retrying HEAD request to https://local:*****@localhost:9104/cozy/ in 128.0 seconds due to error {conn_failed,{error,closed}}
[Fri, 01 Aug 2014 11:54:24 GMT] [error] [<0.2821.0>] Replicator, request HEAD to "https://local:*****@localhost:9104/cozy/" failed due to error {error,{conn_failed,{error,closed}}}
[Fri, 01 Aug 2014 11:54:24 GMT] [info] [<0.2821.0>] 127.0.0.1 - - POST /_replicate 500
[Fri, 01 Aug 2014 11:54:24 GMT] [error] [<0.2821.0>] httpd 500 error response:
 {"error":"error","reason":"Could not open source database `https://local:*****@localhost:9104/cozy/`: {'EXIT',{http_request_failed,\"HEAD\",\n                             \"https://local:*****@localhost:9104/cozy/\",\n                             {error,{error,{conn_failed,{error,closed}}}}}}"}
```

**Comment by frankrousseau** [comment]
Could you add the logs of the proxy? I think the problems come from there.

**Comment by Kloadut** [comment]
Proxy's logs:

```
POST /device/ 200 231ms - 171b
```

**Comment by frankrousseau** [comment]
Hi  @Kloadut. Do you have any news about that issue?

**Comment by aenario** [comment]
Hi all, 

Run into this one today, figured something. @Kloadut made a fix so we now get the proper errors (https://github.com/cozy/cozy-proxy/pull/76), but the proper error is random 401. From what I've seen, it is due to device's doctype "password" field being encrypted and therefore not readable when the user is logged out.

**Comment by Kloadut** [comment]
There is also an issue when re-using a device name (even when deleted). I am investigating on it.

**Comment by bnjbvr** [comment]
Seems to work for me now! Feel free to close the issue if you landed all your fixes.

**Comment by bnjbvr** [comment]
Well, I actually hit random errors 500 when reaching my cozy with my browser, but sync seems to work.

**Comment by frankrousseau** [comment]
This repository is no more maintained. Whatever, thank you @bnjbvr for your feedback.
