### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ghost** [cozy-labs/cozy-fuse#22]
I run into errors on Ubuntu 14.04 LTS 64 Bit. Python Version: 2.7.6

```
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cozy-fuse/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-GwIEby-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cozy-fuse
Storing debug log for failure in /home/greasandev/.pip/pip.log
```

The log says:

```
------------------------------------------------------------
/usr/bin/pip run on Wed Aug 27 15:09:20 2014
[...]
running install_data

error: can't copy 'scripts/init/cozy-fuse': doesn't exist or not a regular file

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cozy-fuse/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-GwIEby-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cozy-fuse
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cozy-fuse/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-GwIEby-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cozy-fuse
```

**Comment by frankrousseau** [comment]
Sorry, we do not support this repository anymore. We are working on a simpler project based on iNotify. It's called [Cozy Desktop](https://github.com/cozy-labs/cozy-desktop). But it's still in development.

If you want to participate to testing let us know. We would be glad to inform you of progress in priority.
