### ISSUE TITLE
Installation and runtime errors

### ISSUE THREAD

**Issue by bnjbvr** [cozy-labs/cozy-fuse#8]
On install:

```
Downloading/unpacking git+https://@github.com/mycozycloud/cozy-fuse-linux.git
  Cloning https://@github.com/mycozycloud/cozy-fuse-linux.git to /tmp/pip-px2FUA-build
  Running setup.py egg_info for package from git+https://@github.com/mycozycloud/cozy-fuse-linux.git

    warning: no files found matching '*' under directory 'cozy-fuse'
Requirement already satisfied (use --upgrade to upgrade): fuse-python>=0.2 in /usr/lib/python2.7/dist-packages (from cozy-fuse==0.1.0)
Downloading/unpacking CouchDB>=0.9 (from cozy-fuse==0.1.0)
  Downloading CouchDB-0.10.tar.gz (56kB): 56kB downloaded
  Running setup.py egg_info for package CouchDB

Downloading/unpacking requests>=2.0.1 (from cozy-fuse==0.1.0)
  Downloading requests-2.3.0.tar.gz (429kB): 429kB downloaded
  Running setup.py egg_info for package requests

Downloading/unpacking pyyaml (from cozy-fuse==0.1.0)
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py egg_info for package pyyaml

Requirement already satisfied (use --upgrade to upgrade): lockfile in /usr/lib/python2.7/dist-packages (from cozy-fuse==0.1.0)
Downloading/unpacking python-daemon (from cozy-fuse==0.1.0)
  Downloading python-daemon-1.6.tar.gz (41kB): 41kB downloaded
  Running setup.py egg_info for package python-daemon

Requirement already satisfied (use --upgrade to upgrade): distribute in /usr/lib/python2.7/dist-packages (from python-daemon->cozy-fuse==0.1.0)
Installing collected packages: CouchDB, requests, pyyaml, python-daemon, cozy-fuse
  Running setup.py install for CouchDB
      File "/usr/local/lib/python2.7/dist-packages/couchdb/util3.py", line 17
        pyexec = exec
                    ^
    SyntaxError: invalid syntax


    Installing couchdb-dump script to /usr/local/bin
    Installing couchpy script to /usr/local/bin
    Installing couchdb-load script to /usr/local/bin
    Installing couchdb-replicate script to /usr/local/bin
  Running setup.py install for requests

  Running setup.py install for pyyaml
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.

    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)

  Running setup.py install for python-daemon

  Running setup.py install for cozy-fuse

    warning: no files found matching '*' under directory 'cozy-fuse'
    Installing cozy-fuse script to /usr/local/bin
Successfully installed CouchDB requests pyyaml python-daemon cozy-fuse
Cleaning up...
```

When running cozy-fuse configure:

```
$ cozy-fuse configure -u https://example.com -n machine-name -p /home/me/cozy-sync 
Traceback (most recent call last):
  File "/usr/local/bin/cozy-fuse", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2809, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 598, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (lockfile 0.8 (/usr/lib/python2.7/dist-packages), Requirement.parse('lockfile>=0.9'))
```

Some debug informations:

```
Python 2.7.5+ (default, Feb 27 2014, 19:37:08) 
[GCC 4.8.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

`pip 1.4.1 from /usr/lib/python2.7/dist-packages (python 2.7)`

**Comment by Kloadut** [comment]
I just updated the README.md, can you follow the install instructions again and retry ?
It looks like a conflict in one of the dependency, thus can you try on a clean environment ?

**Comment by bnjbvr** [comment]
humm, using the last version and `sudo pip install --upgrade cozy-fuse` did the trick. Sorry for the noise.

**Comment by bnjbvr** [comment]
OK, sorry to reopen this one. I've installed cozy-fuse on another computer and ran into the same problem. So my solution was:
1) install cozy-fuse as indicated with pip
2) directly do `sudo pip install --upgrade cozy-fuse`

Might be worth indicating that in the readme. I'll do it, unless you beat me to it ;)
